- name: <nombre_manga_1>
  url: <url_manga_1>
  first_chapter: <first|número_capítulo_inicial>
  last_chapter: <last|número_capítulo_final>
  trim_first_pages: <páginas_iniciales_a_eliminar>
  trim_last_pages: <páginas_finales_a_eliminar>
- name: <nombre_manga_2>
  url: <url_manga_2>
  first_chapter: <first|número_capítulo_inicial>
  last_chapter: <last|número_capítulo_final>
  trim_first_pages: <páginas_iniciales_a_eliminar>
  trim_last_pages: <páginas_finales_a_eliminar>
- name: <nombre_manga_3>
  url: <url_manga_3>
  first_chapter: <first|número_capítulo_inicial>
  last_chapter: <last|número_capítulo_final>
  trim_first_pages: <páginas_iniciales_a_eliminar>
  trim_last_pages: <páginas_finales_a_eliminar>
